"""change visualization_image to MEDIUMBLOB

Revision ID: b897c53ea085
Revises: fcf80e5c7515
Create Date: 2025-11-15 11:01:58.580581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b897c53ea085'
down_revision: Union[str, Sequence[str], None] = 'fcf80e5c7515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('route', 'visualization_image',
               existing_type=sa.BLOB(),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('route', 'visualization_image',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.BLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###
