"""empty message

Revision ID: fcf80e5c7515
Revises: 
Create Date: 2025-11-15 10:59:08.190252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf80e5c7515'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('t_start_idx', sa.Integer(), nullable=False),
    sa.Column('t_goal_idx', sa.Integer(), nullable=False),
    sa.Column('lat_start', sa.Float(), nullable=False),
    sa.Column('lon_start', sa.Float(), nullable=False),
    sa.Column('lat_goal', sa.Float(), nullable=False),
    sa.Column('lon_goal', sa.Float(), nullable=False),
    sa.Column('bcf', sa.Float(), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('w_fuel', sa.Float(), nullable=False),
    sa.Column('w_bc', sa.Float(), nullable=False),
    sa.Column('w_risk', sa.Float(), nullable=False),
    sa.Column('visualization_image', sa.LargeBinary(), nullable=False),
    sa.Column('cost_summary_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route')
    # ### end Alembic commands ###
